version = 1

[[annotations]]
path = [
  ".editorconfig",
  ".envrc",
  ".gitignore",
  ".golangci.yaml",
  "treefmt.toml",
  "typos.toml",
  "go.mod",
  "go.sum",
  "flake.lock",
  "flake.nix",
  "README.md"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
