[formatter.gofumpt]
command = "gofumpt"
excludes = ["vendor/*"]
includes = ["*.go"]
options = ["-w"]

[formatter.golangci-lint]
command = "golangci-lint"
excludes = ["vendor/*"]
includes = ["*.go"]
options = ["run"]

[formatter.nix]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.toml-sort]
command = "toml-sort"
excludes = []
includes = ["*.toml"]
options = ["-i"]
